apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.rendered.yml --out k8s-out --verbose
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: airflow-scheduler
  name: airflow-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: airflow-scheduler
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.rendered.yml --out k8s-out --verbose
        kompose.version: 1.38.0 (HEAD)
      labels:
        io.kompose.service: airflow-scheduler
    spec:
      containers:
        - args:
            - scheduler
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: SequentialExecutor
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://agro_user:agro_password@postgres:5432/brain_agro
          image: apache/airflow:2.6.1
          name: airflow-scheduler
          volumeMounts:
            - mountPath: /opt/airflow/dags
              name: airflow-scheduler-claim0
            - mountPath: /opt/airflow/scripts
              name: airflow-scheduler-claim1
      restartPolicy: Always
      volumes:
        - name: airflow-scheduler-claim0
          persistentVolumeClaim:
            claimName: airflow-scheduler-claim0
        - name: airflow-scheduler-claim1
          persistentVolumeClaim:
            claimName: airflow-scheduler-claim1
