apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.rendered.yml --out k8s-out --verbose
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: airflow-webserver
  name: airflow-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: airflow-webserver
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.rendered.yml --out k8s-out --verbose
        kompose.version: 1.38.0 (HEAD)
      labels:
        io.kompose.service: airflow-webserver
    spec:
      containers:
        - args:
            - bash
            - -c
            - |2
                airflow db upgrade &&
                airflow users create --username admin --firstname Admin --lastname Admin --role Admin --email admin@admin.com --password admin &&
                airflow webserver
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: SequentialExecutor
            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: "False"
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://agro_user:agro_password@postgres:5432/brain_agro
          image: apache/airflow:2.6.1
          name: airflow-webserver
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/airflow/dags
              name: airflow-webserver-claim0
            - mountPath: /opt/airflow/scripts
              name: airflow-webserver-claim1
      restartPolicy: Always
      volumes:
        - name: airflow-webserver-claim0
          persistentVolumeClaim:
            claimName: airflow-webserver-claim0
        - name: airflow-webserver-claim1
          persistentVolumeClaim:
            claimName: airflow-webserver-claim1
