apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.rendered.yml --out k8s-out --verbose
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: cd4ml-api
  name: cd4ml-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cd4ml-api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.rendered.yml --out k8s-out --verbose
        kompose.version: 1.38.0 (HEAD)
      labels:
        io.kompose.service: cd4ml-api
    spec:
      containers:
        - env:
            - name: AWS_ACCESS_KEY_ID
              value: admin
            - name: AWS_SECRET_ACCESS_KEY
              value: adminadmin
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://minio:9000
            - name: MLFLOW_TRACKING_URI
              value: http://mlflow:5000
          image: cd4ml-api
          name: cd4ml-api
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
