apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.rendered.yml --out k8s-out --verbose
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: dev
  name: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dev
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.rendered.yml --out k8s-out --verbose
        kompose.version: 1.38.0 (HEAD)
      labels:
        io.kompose.service: dev
    spec:
      containers:
        - args:
            - jupyter
            - lab
            - --LabApp.token=
          command:
            - start.sh
          env:
            - name: JUPYTER_ENABLE_LAB
              value: "yes"
          image: jupyter/minimal-notebook:54462805efcb
          name: dev
          ports:
            - containerPort: 8888
              protocol: TCP
          volumeMounts:
            - mountPath: /home/jovyan
              name: dev-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: dev-cm0
          name: dev-cm0
