apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.rendered.yml --out k8s-out --verbose
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: es01
  name: es01
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: es01
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.rendered.yml --out k8s-out --verbose
        kompose.version: 1.38.0 (HEAD)
      labels:
        io.kompose.service: es01
    spec:
      containers:
        - env:
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: bootstrap.memory_lock
              value: "true"
            - name: cluster.name
              value: es-docker-cluster
            - name: discovery.type
              value: single-node
            - name: http.host
              value: 0.0.0.0
            - name: http.port
              value: "9200"
            - name: node.name
              value: es01
          image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
          name: es01
          ports:
            - containerPort: 9200
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: data01
      restartPolicy: Always
      volumes:
        - name: data01
          persistentVolumeClaim:
            claimName: data01
