apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.rendered.yml --out k8s-out --verbose
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: fluentd
  name: fluentd
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fluentd
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.rendered.yml --out k8s-out --verbose
        kompose.version: 1.38.0 (HEAD)
      labels:
        io.kompose.service: fluentd
    spec:
      containers:
        - image: ericnaglertw/cd4ml-fluentd:1
          name: fluentd
          ports:
            - containerPort: 24224
              protocol: TCP
          volumeMounts:
            - mountPath: /fluentd/etc
              name: fluentd-claim0
      restartPolicy: Always
      volumes:
        - name: fluentd-claim0
          persistentVolumeClaim:
            claimName: fluentd-claim0
