apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.rendered.yml --out k8s-out --verbose
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: jenkins
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jenkins
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.rendered.yml --out k8s-out --verbose
        kompose.version: 1.38.0 (HEAD)
      labels:
        io.kompose.service: jenkins
    spec:
      containers:
        - env:
            - name: ACCESS_KEY
              value: admin
            - name: FLUENTD_HOST
              value: fluentd
            - name: FLUENTD_PORT
              value: "24224"
            - name: SECRET_KEY
              value: adminadmin
            - name: TENANT
              value: jenkins
          image: jenkins
          livenessProbe:
            exec:
              command:
                - curl -s http://localhost:8080/login || exit 1
            failureThreshold: 5
            periodSeconds: 30
            timeoutSeconds: 10
          name: jenkins
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: "2"
              memory: "8589934592"
            requests:
              cpu: "1"
              memory: "4294967296"
          volumeMounts:
            - mountPath: /run/secrets
              name: jenkins-admin-password
              subPath: jenkins-admin-password
            - mountPath: /var/jenkins_home
              name: jenkins-home
      restartPolicy: Always
      volumes:
        - name: jenkins-admin-password
          secret:
            items:
              - key: jenkins-admin-password
                path: jenkins-admin-password
            secretName: jenkins-admin-password
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-home
