apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.rendered.yml --out k8s-out --verbose
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: kib01
  name: kib01
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kib01
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.rendered.yml --out k8s-out --verbose
        kompose.version: 1.38.0 (HEAD)
      labels:
        io.kompose.service: kib01
    spec:
      containers:
        - env:
            - name: ELASTICSEARCH_HOSTS
              value: http://es01:9200
            - name: ELASTICSEARCH_URL
              value: http://es01:9200
          image: docker.elastic.co/kibana/kibana:7.6.0
          name: kib01
          ports:
            - containerPort: 5601
              protocol: TCP
      restartPolicy: Always
