apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.rendered.yml --out k8s-out --verbose
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: pgadmin
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pgadmin
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.rendered.yml --out k8s-out --verbose
        kompose.version: 1.38.0 (HEAD)
      labels:
        io.kompose.service: pgadmin
    spec:
      containers:
        - env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: admin@admin.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: admin
          image: dpage/pgadmin4
          livenessProbe:
            exec:
              command:
                - curl
                - -s
                - http://localhost:80 || exit 1
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 10
          name: pgadmin
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
